language: java
dist: trusty
sudo: false
cache:
  directories:
    - $HOME/.gradle
notifications:
  email: false
jdk:
  - oraclejdk8
before_install:
  - chmod a+x gradlew
install: true
script: ./gradlew clean build -S
